-- 자동차 ID, 자동차 종류, 대여 금액 추출
-- 자동차 종류가 세단 or SUV
-- 2022년 11월 대여 가능 -> 시작일이 11/1보다 작고, 종료일이 11/30보다 큰 경우
-- 30일간 대여 금액이 50만원 이상 200만원 미만

SELECT 
  C.CAR_ID AS CAR_ID, 
  C.CAR_TYPE AS CAR_TYPE, 
  ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
  SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-12-01'
  AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
) 
AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV')
  AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC