SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(date_of_birth, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE date_of_birth LIKE '%03%' 
AND tlno is not NULL
AND GENDER = 'W'
ORDER BY MEMBER_ID