SELECT TITLE, ugb.BOARD_ID, REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') AS CREATEDDATE
FROM USED_GOODS_BOARD ugb JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE LEFT(ugb.CREATED_DATE, 7) = '2022-10'
ORDER BY ugr.CREATED_DATE, ugb.TITLE