-- SELECT DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
-- FROM DOCTOR
-- WHERE 3 IN ('CS', 'GS')
-- ORDER BY 4 DESC 1;

SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%U-%M-%D')
FROM DOCTOR
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME;

SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD,'%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD IN ('CS','GS')
ORDER BY HIRE_YMD DESC, DR_NAME