-- 코드를 입력하세요
-- USED_GOODS_BOARD : BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, CREATED_DATE, STATUS, VIEWS
-- USED_GOODS_FILE : FILE_ID, FILE_EXT, FILE_NAME, BOARD_ID
-- FILE_ID,FILE_NAME,FILE_EXT
-- 테이블간의 관계 고려하기!!
-- 이 문제의 경우, 같은 Board 내에 여러 개의 첨부파일이 들어갈 수 있음

WITH most_view AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT 
    CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (SELECT BOARD_ID FROM most_view)
ORDER BY FILE_ID DESC