-- 코드를 입력하세요
-- ANIMAL_INS : ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE

WITH count_name as (
    SELECT NAME, COUNT(NAME) AS COUNT
    FROM ANIMAL_INS
    GROUP BY NAME
)

SELECT *
FROM count_name
WHERE COUNT >= 2
ORDER BY NAME