-- 코드를 입력하세요
-- FIRST_HALF : SHIPMENT_ID, FLAVOR(기본키), TOTAL_ORDER
-- JULY : SHIPMENT_ID, FLAVOR, TOTAL_ORDER
WITH JULY AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR
FROM FIRST_HALF FH INNER JOIN JULY J ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.TOTAL_ORDER + J.JULY_TOTAL_ORDER) DESC
LIMIT 3