WITH A AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY 1
), B AS (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
)

SELECT A.YEAR, (A.MAX_COLONY - B.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM A INNER JOIN B ON A.YEAR = B.YEAR
ORDER BY 1, 2