SELECT PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM (
    SELECT CASE 
        WHEN FLOOR(PRICE / 10000) = 0 THEN 0
        ELSE CONCAT(FLOOR(PRICE / 10000), '0000')
       END AS PRICE_GROUP
    FROM PRODUCT
) B
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP