-- 코드를 입력하세요
-- USER_INFO : USER_ID, GENDER, AGE, JOINED
-- ONLINE_SALE : ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- GENDER는 0인 경우 남자, 1인 경우 여자

SELECT YEAR(ONLINE_SALE.SALES_DATE) AS YEAR, 
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH, 
    USER_INFO.GENDER, 
    COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM USER_INFO INNER JOIN ONLINE_SALE 
    ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1, 2, 3