WITH RENTAL AS (
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT CR.CAR_ID, IFNULL(RENTAL.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR 
    LEFT JOIN RENTAL ON CR.CAR_ID = RENTAL.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC