SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT CATEGORY, BOOK.AUTHOR_ID, PRICE*SALES AS TOTAL_SALES, AUTHOR_NAME, SALES_DATE
    FROM BOOK_SALES BS INNER JOIN BOOK ON BS.BOOK_ID = BOOK.BOOK_ID
        INNER JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
) A
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 1, 3
ORDER BY 1, 3 DESC