WITH GROUP_CTA AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE USED_GOODS_BOARD.STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT ugu.USER_ID, ugu.NICKNAME, gc.TOTAL_PRICE AS TOTAL_SALES
FROM GROUP_CTA gc INNER JOIN USED_GOODS_USER ugu ON gc.WRITER_ID = ugu.USER_ID
WHERE gc.TOTAL_PRICE >= 700000
ORDER BY gc.TOTAL_PRICE